customSiteSettings.siteSettings_form:
  path: '/custom-site-settings'
  defaults:
    _form: 'Drupal\customSiteSettings\Form\SiteSettingsForm'
    _title: 'Custom site setting form'
  requirements:
    _permission: 'access content'